version: '3.9'

services:
  escolinha:
    container_name: escolinha
    build:
      context: .
    command: [ "sh", "/scripts/commands.sh" ]
    ports:
      - "8000:8000"
    volumes:
      - .:/escolinha
      #- ./escolinha:/escolinha
      - ./scripts:/scripts
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db

  db:
    container_name: psql
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: escolinha_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 34587895
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pg_data:
  pgadmin_data:
