# Generated by Django 5.1.11 on 2025-06-20 18:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import home.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(default=home.utils.gerar_matricula_unica, max_length=20, unique=True)),
                ('nome', models.CharField(default='', max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('rg', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sexo', models.CharField(default='', max_length=10)),
                ('nacionalidade', models.CharField(default='', max_length=50)),
                ('naturalidade', models.CharField(default='', max_length=50)),
                ('certidao_numero', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('certidao_livro', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tipo_sanguineo', models.CharField(default='', max_length=3)),
                ('rua', models.CharField(default='', max_length=100)),
                ('numero', models.CharField(default='', max_length=10)),
                ('cep', models.CharField(default='', max_length=10)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('cidade', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=2)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ inválido', regex='^\\d{14}$')])),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(default='00000000', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('role', models.CharField(choices=[('professor', 'Professor'), ('diretor', 'Diretor'), ('coordenador', 'Coordenador'), ('secretaria', 'Secretária'), ('responsavel', 'Responsável')], default='funcionario', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='home_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='home_user_permissions', to='auth.permission')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacao_saida_sozinho', models.BooleanField(default=False)),
                ('autorizacao_fotos_eventos', models.BooleanField(default=False)),
                ('pessoa_autorizada_buscar', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=14, unique=True)),
                ('nascimento', models.DateField(default='1900-01-01')),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('cep', models.CharField(default='000000000', max_length=9)),
                ('endereco', models.CharField(default='', max_length=100)),
                ('numero', models.CharField(default='', max_length=10)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(default='Bairro', max_length=50)),
                ('cidade', models.CharField(default='Cidade', max_length=50)),
                ('estado', models.CharField(default='PE', max_length=2)),
                ('cargo', models.CharField(default='Professor', max_length=50)),
                ('formacao', models.CharField(default='', max_length=100)),
                ('experiencia', models.TextField(default='')),
                ('ativo', models.BooleanField(default=True)),
                ('disciplinas', models.ManyToManyField(blank=True, to='home.disciplina')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('data_termino', models.DateField()),
                ('hora_termino', models.TimeField()),
                ('especialidade', models.CharField(max_length=255)),
                ('tipo_plantao', models.CharField(max_length=20)),
                ('quantidade_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('professor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('parentesco', models.CharField(default='', max_length=50)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_necessidade_especial', models.BooleanField(default=False)),
                ('descricao_necessidade', models.TextField(blank=True, default='', null=True)),
                ('usa_medicacao', models.BooleanField(default=False)),
                ('quais_medicacoes', models.TextField(blank=True, default='', null=True)),
                ('possui_alergia', models.BooleanField(default=False)),
                ('descricao_alergia', models.TextField(blank=True, default='', null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='TransporteEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_transporte_escolar', models.BooleanField(default=False)),
                ('trajeto', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('sala', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas', to='home.aluno')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('professores', models.ManyToManyField(blank=True, related_name='turmas', to='home.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='home.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'bimestre', 'escola')},
            },
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'unique_together': {('turma', 'disciplina', 'professor')},
            },
        ),
    ]
