# Generated by Django 5.0.7 on 2025-11-25 21:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import home.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(default=home.utils.gerar_matricula_unica, max_length=20, unique=True)),
                ('nome', models.CharField(default='', max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('rg', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sexo', models.CharField(default='', max_length=10)),
                ('nacionalidade', models.CharField(default='', max_length=50)),
                ('naturalidade', models.CharField(default='', max_length=50)),
                ('certidao_numero', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('certidao_livro', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tipo_sanguineo', models.CharField(default='', max_length=3)),
                ('rua', models.CharField(default='', max_length=100)),
                ('numero', models.CharField(default='', max_length=10)),
                ('cep', models.CharField(default='', max_length=10)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('cidade', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=2)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
                ('cor_raca', models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena'), ('nao_informado', 'Não informado')], max_length=20, null=True)),
                ('responsavel_financeiro', models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('outro', 'Outro')], max_length=10, null=True)),
                ('situacao_familiar', models.CharField(blank=True, choices=[('casados', 'Casados'), ('separados', 'Separados'), ('outros', 'Outros')], max_length=12, null=True)),
                ('dispensa_ensino_religioso', models.BooleanField(default=False)),
                ('forma_acesso', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao_matricula', models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('rematricula', 'Rematrícula'), ('transferencia', 'Transferência')], max_length=20, null=True)),
                ('bolsa_familia', models.BooleanField(default=False)),
                ('serie_ano', models.CharField(blank=True, max_length=50)),
                ('turno_aluno', models.CharField(blank=True, max_length=20)),
                ('possui_necessidade_especial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ inválido', regex='^\\d{14}$')])),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone inválido', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')])),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(default='00000000', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(blank=True, help_text='CPF do usuário (apenas números)', max_length=11, null=True, unique=True)),
                ('role', models.CharField(choices=[('professor', 'Professor'), ('diretor', 'Diretor'), ('coordenador', 'Coordenador'), ('secretaria', 'Secretária'), ('responsavel', 'Responsável')], default='responsavel', max_length=20)),
                ('senha_temporaria', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacao_saida_sozinho', models.BooleanField(default=False)),
                ('autorizacao_fotos_eventos', models.BooleanField(default=False)),
                ('pessoa_autorizada_buscar', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('usa_transporte_publico', models.BooleanField(default=False)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=14, unique=True)),
                ('nascimento', models.DateField(default='1900-01-01')),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('cep', models.CharField(default='000000000', max_length=9)),
                ('endereco', models.CharField(default='', max_length=100)),
                ('numero', models.CharField(default='', max_length=10)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(default='Bairro', max_length=50)),
                ('cidade', models.CharField(default='Cidade', max_length=50)),
                ('estado', models.CharField(default='PE', max_length=2)),
                ('cargo', models.CharField(default='Professor', max_length=50)),
                ('formacao', models.CharField(default='', max_length=100)),
                ('experiencia', models.TextField(default='')),
                ('sexo', models.CharField(default='Masculino', max_length=50)),
                ('ativo', models.CharField(default='Sim', max_length=9)),
                ('disciplinas', models.ManyToManyField(blank=True, to='home.disciplina')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='home.escola')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('parentesco', models.CharField(default='', max_length=50)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('tipo', models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('outro', 'Outro')], max_length=10, null=True)),
                ('identidade', models.CharField(blank=True, max_length=30, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=60, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_necessidade_especial', models.BooleanField(default=False)),
                ('descricao_necessidade', models.TextField(blank=True, default='', null=True)),
                ('usa_medicacao', models.BooleanField(default=False)),
                ('quais_medicacoes', models.TextField(blank=True, default='', null=True)),
                ('possui_alergia', models.BooleanField(default=False)),
                ('descricao_alergia', models.TextField(blank=True, default='', null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='TransporteEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_transporte_escolar', models.BooleanField(default=False)),
                ('trajeto', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('sala', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas', to='home.aluno')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('professores', models.ManyToManyField(blank=True, related_name='turmas', to='home.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'unique_together': {('data', 'turma', 'disciplina', 'professor')},
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_principais', to='home.turma'),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chamada')),
            ],
            options={
                'unique_together': {('chamada', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('media_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recuperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'turma', 'escola')},
            },
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'unique_together': {('turma', 'disciplina', 'professor')},
            },
        ),
    ]
