# Generated by Django 5.0.7 on 2025-11-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0001_initial'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='nota',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='aluno',
            name='bolsa_familia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cor_raca',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena'), ('nao_informado', 'Não informado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dispensa_ensino_religioso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='forma_acesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_financeiro',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='serie_ano',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_familiar',
            field=models.CharField(blank=True, choices=[('casados', 'Casados'), ('separados', 'Separados'), ('outros', 'Outros')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_matricula',
            field=models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('rematricula', 'Rematrícula'), ('transferencia', 'Transferência')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_principais', to='home.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turno_aluno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='autorizacoes',
            name='usa_transporte_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docente',
            name='sexo',
            field=models.CharField(default='Masculino', max_length=50),
        ),
        migrations.AddField(
            model_name='nota',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.turma'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='identidade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='profissao',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='tipo',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.AddField(
            model_name='user',
            name='senha_temporaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='ativo',
            field=models.CharField(default='Sim', max_length=9),
        ),
        migrations.AlterField(
            model_name='docente',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='home.escola'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do usuário (apenas números)', max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professor', 'Professor'), ('diretor', 'Diretor'), ('coordenador', 'Coordenador'), ('secretaria', 'Secretária'), ('responsavel', 'Responsável')], default='responsavel', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'disciplina', 'turma', 'bimestre', 'escola')},
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'unique_together': {('data', 'turma', 'disciplina', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chamada')),
            ],
            options={
                'unique_together': {('chamada', 'aluno')},
            },
        ),
    ]
