# Generated by Django 5.1.11 on 2025-06-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='senha_temporaria',
            field=models.BooleanField(default=False),
        ),
    ]
