# Generated by Django 5.0.7 on 2025-11-26 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
        ),
    ]
