# Generated by Django 5.1.11 on 2025-06-23 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_senha_temporaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
    ]
