# Generated by Django 5.0.7 on 2025-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_possui_necessidade_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='tipo',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('responsavel', 'Responsável')], max_length=12, null=True),
        ),
    ]
