# Generated by Django 5.1.11 on 2025-06-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_disciplina_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='home.escola'),
        ),
    ]
