# Generated by Django 5.1.11 on 2025-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_docente_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='ativo',
        ),
        migrations.AddField(
            model_name='docente',
            name='sexo',
            field=models.CharField(default='Masculino', max_length=50),
        ),
    ]
