# Generated by Django 5.1.11 on 2025-06-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_docente_ativo_docente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='ativo',
            field=models.CharField(default='Sim', max_length=9),
        ),
    ]
