# Generated by Django 5.0.7 on 2025-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacoes',
            name='pessoa_autorizada_buscar',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
