# Generated by Django 5.1.11 on 2025-06-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_docente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmadisciplina',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='escola',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
    ]
