# Generated by Django 5.1.11 on 2025-06-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_turmadisciplina_escola_alter_nota_escola'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nota',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.turma'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'disciplina', 'turma', 'bimestre', 'escola')},
        ),
    ]
