# Generated by Django 5.1.11 on 2025-07-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_chamada_presenca'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chamada',
            unique_together={('data', 'turma', 'disciplina', 'professor')},
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('chamada', 'aluno')},
        ),
    ]
