# Generated by Django 5.1.13 on 2025-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_chamada_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cor_raca',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena'), ('nao_informado', 'Não informado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dispensa_ensino_religioso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='forma_acesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_financeiro',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_familiar',
            field=models.CharField(blank=True, choices=[('casados', 'Casados'), ('separados', 'Separados'), ('outros', 'Outros')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='autorizacoes',
            name='usa_transporte_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='identidade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='profissao',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='tipo',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('outro', 'Outro')], max_length=10, null=True),
        ),
    ]
