# Generated by Django 5.1.13 on 2025-10-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_aluno_cor_raca_aluno_data_ingresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bolsa_familia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='serie_ano',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_matricula',
            field=models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('rematricula', 'Rematrícula'), ('transferencia', 'Transferência')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_principais', to='home.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turno_aluno',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
